language: java

jdk:
  - openjdk8

branches:
  only:
    - master

script: ./gradlew check

after_success:
  # upload report to codecov
  - bash <(curl -s https://codecov.io/bash)
  # publish ascii doctor docs
  - ./gradlew asciidoctor
  - git submodule add -b gh-pages https://${GH_OAUTH_TOKEN}@github.com/${GH_OWNER}/${GH_PROJECT_NAME} site > /dev/null 2>&1
  - cd site
  - git rm -r .
  - cp -R ../build/asciidoc/html5/* .
  - git add -f .
  - git config user.name "AlphaHinex"
  - git config user.email "AlphaHinex@gmail.com"
  - DATE=`date +%Y-%m-%d`
  - TIME=`date +%H:%M:%S`
  - git commit -am "Travis CI synchronized gh-pages at $DATE $TIME"
  - git push https://${GH_OAUTH_TOKEN}@github.com/${GH_OWNER}/${GH_PROJECT_NAME} HEAD:gh-pages > /dev/null 2>&1
