name: 'Auto publish release tag to GitHub Packages'

on:
  push:
    tags:
      - v*.RELEASE

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew publish
      env:
        GH_OWNER: AlphaHinex
        GH_PKG_ADMIN: ${{ secrets.GITHUB_TOKEN }}
